/**
 * Builds the downloadable design-system kit from LIVE source — the zip can
 * never drift from the repo because it IS the repo, sliced by the manifest.
 *
 *   npm run build:kit   →  public/qubetx-design-system.zip  (stable permalink)
 *
 * Contents: agent docs (README/SKILL/MOTION_GUIDE), DESIGN_SYSTEM.md,
 * tokens/qubetx-tokens.css (sliced from app/globals.css between the
 * @kit-tokens markers), fonts/fonts.css (@font-face for standalone use),
 * package-snippet.json (exact dep versions), and the source layers listed
 * in kit/manifest.mjs. Run it whenever kit contents change and commit the
 * zip (static export serves it; CI never needs to run this).
 */

import { createWriteStream } from 'node:fs'
import { mkdir, readdir, readFile, stat, unlink } from 'node:fs/promises'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { KIT_DIRS, KIT_FILES, KIT_DEPENDENCIES, KIT_DEV_DEPENDENCIES } from '../kit/manifest.mjs'

// archiver v8 is CommonJS exporting classes — load through createRequire
const require = createRequire(import.meta.url)
const { ZipArchive } = require('archiver')

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const pkg = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'))
const version = pkg.version
// Version-STABLE filename: /qubetx-design-system.zip is a copyable permalink
// that always serves the current build. Version lives inside the zip (docs,
// tokens header, package-snippet) and in the saved filename via the sidebar
// link's `download` attribute (DS_KIT_FILENAME).
const outName = 'qubetx-design-system.zip'
const outPath = path.join(root, 'public', outName)
const prefix = 'qubetx-design-system/'

/* ---- Generated: tokens/qubetx-tokens.css -------------------------------- */
async function buildTokensCss() {
  const globals = await readFile(path.join(root, 'app', 'globals.css'), 'utf8')
  const start = globals.indexOf('/* @kit-tokens-start')
  const end = globals.indexOf('/* @kit-tokens-end */')
  if (start === -1 || end === -1) {
    throw new Error('globals.css is missing the @kit-tokens markers')
  }
  const block = globals.slice(start, end + '/* @kit-tokens-end */'.length)
  return `/* =============================================================================
   QubeTX design tokens — v${version}
   Generated by scripts/build-kit.mjs from app/globals.css (do not edit;
   the landing repo is the source of truth).

   Next.js projects: copy the :root block into app/globals.css and wire the
   fonts via next/font/local (src/fonts/index.ts in this kit).
   Standalone/non-Next: load fonts/fonts.css first, then this file — the
   literal-family fallback at the bottom maps the font variables.
   ============================================================================= */

${block}

/* Standalone fallback (no next/font): after loading fonts/fonts.css the
   literal families satisfy the stacks above. */
:root {
  --font-makira: 'Makira';
  --font-plex-mono: 'IBM Plex Mono';
}
`
}

/* ---- Generated: fonts/fonts.css ------------------------------------------ */
function buildFontsCss() {
  const face = (family, file, weight) => `@font-face {
  font-family: '${family}';
  src: url('./${file}') format('woff2');
  font-weight: ${weight};
  font-display: swap;
}`
  return [
    `/* QubeTX kit fonts — for standalone (non-Next) use; Next.js projects use
   next/font/local via src/fonts/index.ts instead. */`,
    face('Makira', 'Makira-Regular.woff2', 400),
    face('Makira', 'Makira-Medium.woff2', 500),
    face('Makira', 'Makira-Bold.woff2', 700),
    face('Makira', 'Makira-Black.woff2', 900),
    face('IBM Plex Mono', 'IBMPlexMono-Regular.woff2', 400),
    face('IBM Plex Mono', 'IBMPlexMono-Medium.woff2', 500),
    face('IBM Plex Mono', 'IBMPlexMono-SemiBold.woff2', 600),
  ].join('\n\n')
}

/* ---- Generated: package-snippet.json ------------------------------------- */
function buildPackageSnippet() {
  const pick = (names, fromBlock) =>
    Object.fromEntries(
      names.map((name) => [name, fromBlock?.[name] ?? 'latest']).sort(([a], [b]) => a.localeCompare(b))
    )
  return JSON.stringify(
    {
      '//': `QubeTX design-system kit v${version} — merge into your package.json`,
      dependencies: pick(KIT_DEPENDENCIES, pkg.dependencies),
      devDependencies: pick(KIT_DEV_DEPENDENCIES, pkg.devDependencies),
    },
    null,
    2
  )
}

/* ---- Walk + zip ----------------------------------------------------------- */
async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) files.push(...(await walk(full)))
    else files.push(full)
  }
  return files
}

async function main() {
  // Validate the manifest before writing anything
  for (const { from } of [...KIT_DIRS, ...KIT_FILES]) {
    await stat(path.join(root, from)) // throws loudly on a rename
  }

  await mkdir(path.dirname(outPath), { recursive: true })
  await unlink(outPath).catch(() => {})
  // Remove stale versioned zips from the pre-permalink era so public/ serves exactly one
  for (const name of await readdir(path.join(root, 'public'))) {
    if (name.startsWith('qubetx-design-system-') && name.endsWith('.zip') && name !== outName) {
      await unlink(path.join(root, 'public', name))
    }
  }

  const output = createWriteStream(outPath)
  const archive = new ZipArchive({ zlib: { level: 9 } })
  const done = new Promise((resolve, reject) => {
    output.on('close', resolve)
    archive.on('error', reject)
  })
  archive.pipe(output)

  archive.append(await buildTokensCss(), { name: `${prefix}tokens/qubetx-tokens.css` })
  archive.append(buildFontsCss(), { name: `${prefix}fonts/fonts.css` })
  archive.append(buildPackageSnippet(), { name: `${prefix}package-snippet.json` })

  // Standalone font copies (next projects use src/fonts/, also included)
  for (const file of await walk(path.join(root, 'src', 'fonts'))) {
    if (file.endsWith('.woff2')) {
      archive.file(file, { name: `${prefix}fonts/${path.basename(file)}` })
    }
  }

  for (const { from, to } of KIT_DIRS) {
    for (const file of await walk(path.join(root, from))) {
      const rel = path.relative(path.join(root, from), file).split(path.sep).join('/')
      archive.file(file, { name: `${prefix}${to}/${rel}` })
    }
  }
  for (const { from, to } of KIT_FILES) {
    archive.file(path.join(root, from), { name: `${prefix}${to}` })
  }

  await archive.finalize()
  await done
  const { size } = await stat(outPath)
  console.log(`kit → public/${outName} (${(size / 1024 / 1024).toFixed(2)} MB)`)
}

await main()
